//! Merger: reads scanned files (parallel, chunked to bound memory), redacts
//! secrets, and writes one markdown document with collision-proof fences, a
//! real directory tree, a linked table of contents, and a Merge Report that
//! lists every skipped file with its reason.
//!
//! v7.2 rewrite highlights:
//! - Dynamic fences: each file gets a fence one backtick longer than the
//!   longest run inside it, so markdown-heavy repos can't break the structure.
//! - No more per-file canonicalize/sensitive/size re-checks (the scanner's
//!   verdict is trusted) and no mmap (files are capped at 2 MB anyway).
//! - Chunked parallel processing (64 files at a time) instead of materializing
//!   the whole output in RAM; progress is emitted as files are written.
//! - UTF-8 BOM stripped; lossy decodes are counted and reported.

use std::fs::File;
use std::io::{BufReader, BufWriter, Read, Write};
use std::path::{Path, PathBuf};
use std::sync::atomic::{AtomicBool, Ordering};

use anyhow::Result;
use rayon::prelude::*;

use crate::scanner::SkipEntry;

/// Files processed per parallel batch — bounds peak memory to roughly
/// CHUNK × max_file_size while keeping all cores busy.
const CHUNK: usize = 64;

/// Cap on per-file lines in the Merge Report
const MANIFEST_MAX: usize = 500;

#[derive(Debug, Default)]
pub struct MergeOutcome {
    pub total_bytes: usize,
    pub files_processed: usize,
    pub files_skipped: usize,
    pub secrets_redacted: usize,
    /// bytes/4 heuristic (o200k-ish; Claude runs ~15–20% higher)
    pub token_estimate: usize,
}

struct Processed {
    relative: String,
    content: String,
    fence: String,
    lang: String,
    utf8_note: Option<String>,
    redactions: Vec<(&'static str, usize)>,
}

/// (relative_path, reason) for a file dropped at merge time
type MergeSkip = (String, String);

/// Merge files with progress reporting and cancellation support.
#[allow(clippy::too_many_arguments)]
pub fn merge_files_with_progress<F>(
    root: &Path,
    files: &[PathBuf],
    output: &Path,
    include_tree: bool,
    redact: bool,
    cancel_flag: &AtomicBool,
    mut progress_callback: F,
    scan_skips: &[SkipEntry],
) -> Result<MergeOutcome>
where
    F: FnMut(usize, usize, &str),
{
    let mut writer = BufWriter::with_capacity(256 * 1024, File::create(output)?);
    let total_files = files.len();

    // Header — raw folder name for display (sanitization is for filenames only)
    let folder_display = root
        .file_name()
        .and_then(|n| n.to_str())
        .unwrap_or("Project");
    writeln!(writer, "# {} — Merged Codebase\n", folder_display)?;
    writeln!(
        writer,
        "> Generated by TurboMerger v{}",
        env!("CARGO_PKG_VERSION")
    )?;
    writeln!(
        writer,
        "> Files scanned: {} (merged/skipped detail in the Merge Report at the end)",
        total_files
    )?;
    writeln!(writer, "> Source: {}\n", root.display())?;
    writeln!(writer, "---\n")?;

    if include_tree {
        writeln!(writer, "## Project Structure\n")?;
        writeln!(writer, "```")?;
        write!(writer, "{}", generate_tree(root, files))?;
        writeln!(writer, "```\n")?;
        writeln!(writer, "## Contents\n")?;
        for f in files {
            let rel = relative_display(root, f);
            writeln!(writer, "- [{}](#{})", rel, anchor_for(&rel))?;
        }
        writeln!(writer)?;
        writeln!(writer, "---\n")?;
    }

    let mut outcome = MergeOutcome::default();
    let mut merge_skips: Vec<SkipEntry> = Vec::new();
    let mut decode_notes: Vec<String> = Vec::new();
    let mut redaction_lines: Vec<String> = Vec::new();
    let mut done = 0usize;

    'outer: for chunk in files.chunks(CHUNK) {
        if cancel_flag.load(Ordering::Relaxed) {
            break;
        }

        let mut processed: Vec<(usize, Result<Processed, MergeSkip>)> = chunk
            .par_iter()
            .enumerate()
            .map(|(i, path)| (i, process_file(path, root, redact)))
            .collect();
        processed.sort_by_key(|(i, _)| *i);

        for (_, res) in processed {
            if cancel_flag.load(Ordering::Relaxed) {
                break 'outer;
            }
            done += 1;
            match res {
                Ok(p) => {
                    progress_callback(done, total_files, &p.relative);

                    writeln!(writer, "## {}\n", p.relative)?;
                    writeln!(writer, "{}{}", p.fence, p.lang)?;
                    writer.write_all(p.content.as_bytes())?;
                    if !p.content.ends_with('\n') {
                        writeln!(writer)?;
                    }
                    writeln!(writer, "{}\n", p.fence)?;

                    outcome.total_bytes += p.content.len();
                    outcome.token_estimate += p.content.len() / 4;
                    outcome.files_processed += 1;
                    for (rule, n) in &p.redactions {
                        outcome.secrets_redacted += n;
                        redaction_lines.push(format!("- `{}` — {} × {}", p.relative, n, rule));
                    }
                    if let Some(note) = p.utf8_note {
                        decode_notes.push(format!("- `{}` — {}", p.relative, note));
                    }
                }
                Err((rel, reason)) => {
                    progress_callback(done, total_files, &rel);
                    outcome.files_skipped += 1;
                    merge_skips.push(SkipEntry { path: rel, reason });
                }
            }
        }
    }

    // ---- Merge Report -------------------------------------------------
    writeln!(writer, "---\n")?;
    writeln!(writer, "## Merge Report\n")?;
    writeln!(writer, "- Files merged: {}", outcome.files_processed)?;
    writeln!(
        writer,
        "- Estimated tokens: ~{} (bytes/4 heuristic; Claude counts ~15-20% higher)",
        outcome.token_estimate
    )?;
    if outcome.secrets_redacted > 0 {
        writeln!(
            writer,
            "- Secrets redacted: {} (see Redactions below)",
            outcome.secrets_redacted
        )?;
    }

    let total_skips = scan_skips.len() + merge_skips.len();
    if total_skips > 0 {
        writeln!(
            writer,
            "\n### Skipped files ({} at scan, {} at merge)\n",
            scan_skips.len(),
            merge_skips.len()
        )?;
        for e in scan_skips
            .iter()
            .chain(merge_skips.iter())
            .take(MANIFEST_MAX)
        {
            writeln!(writer, "- `{}` — {}", e.path, e.reason)?;
        }
        if total_skips > MANIFEST_MAX {
            writeln!(writer, "- …and {} more", total_skips - MANIFEST_MAX)?;
        }
    }

    if !redaction_lines.is_empty() {
        writeln!(writer, "\n### Redactions\n")?;
        for line in &redaction_lines {
            writeln!(writer, "{}", line)?;
        }
    }

    if !decode_notes.is_empty() {
        writeln!(writer, "\n### Decoding notes\n")?;
        for line in &decode_notes {
            writeln!(writer, "{}", line)?;
        }
    }

    writer.flush()?;
    Ok(outcome)
}

/// Read + decode + redact a single already-vetted file.
/// The scanner has vetted path safety, size, and binary-ness by extension;
/// only a cheap content re-check remains (text extension but binary payload).
fn process_file(path: &Path, root: &Path, redact: bool) -> Result<Processed, MergeSkip> {
    let relative = relative_display(root, path);

    let file = match File::open(path) {
        Ok(f) => f,
        Err(e) => return Err((relative, format!("unreadable: {}", e))),
    };
    let mut buffer = Vec::new();
    if BufReader::new(file).read_to_end(&mut buffer).is_err() {
        return Err((relative, "unreadable".into()));
    }

    if !buffer.is_empty() {
        let check = 8192.min(buffer.len());
        if crate::security::is_binary_content(&buffer[..check]) {
            return Err((relative, "binary content".into()));
        }
    }

    // Strip UTF-8 BOM so it doesn't leak into the merged document
    if buffer.starts_with(&[0xEF, 0xBB, 0xBF]) {
        buffer.drain(..3);
    }

    let (content, utf8_note) = match String::from_utf8(buffer) {
        Ok(s) => (s, None),
        Err(e) => {
            let bytes = e.into_bytes();
            let s = String::from_utf8_lossy(&bytes).into_owned();
            let n = s.matches('\u{FFFD}').count();
            (
                s,
                Some(format!(
                    "not valid UTF-8 — {} byte(s) replaced with U+FFFD (consider re-saving as UTF-8)",
                    n
                )),
            )
        }
    };

    let (content, redactions) = if redact {
        let (clean, events) = crate::security::redact_secrets(&content);
        (
            clean,
            events.into_iter().map(|ev| (ev.rule, ev.count)).collect(),
        )
    } else {
        (content, Vec::new())
    };

    // Dynamic fence: one backtick longer than the longest run inside (min 3)
    let fence = "`".repeat((longest_backtick_run(&content) + 1).max(3));
    let lang = Path::new(&relative)
        .extension()
        .and_then(|e| e.to_str())
        .unwrap_or("")
        .to_string();

    Ok(Processed {
        relative,
        content,
        fence,
        lang,
        utf8_note,
        redactions,
    })
}

fn relative_display(root: &Path, path: &Path) -> String {
    path.strip_prefix(root)
        .map(|p| p.to_string_lossy().replace('\\', "/"))
        .unwrap_or_else(|_| path.to_string_lossy().to_string())
}

fn longest_backtick_run(s: &str) -> usize {
    let mut max = 0;
    let mut cur = 0;
    for b in s.bytes() {
        if b == b'`' {
            cur += 1;
            if cur > max {
                max = cur;
            }
        } else {
            cur = 0;
        }
    }
    max
}

/// GitHub-style anchor slug for a heading whose text is `rel`
fn anchor_for(rel: &str) -> String {
    rel.chars()
        .filter_map(|c| {
            let c = c.to_ascii_lowercase();
            if c.is_ascii_alphanumeric() {
                Some(c)
            } else if c == ' ' || c == '-' {
                Some('-')
            } else {
                None
            }
        })
        .collect()
}

/// Proper recursive tree (the v7.1 version rendered a flat two-level listing
/// with misleading connectors).
fn generate_tree(root: &Path, files: &[PathBuf]) -> String {
    #[derive(Default)]
    struct Node {
        dirs: std::collections::BTreeMap<String, Node>,
        files: Vec<String>,
    }

    let mut top = Node::default();
    for f in files {
        if let Ok(rel) = f.strip_prefix(root) {
            let comps: Vec<String> = rel
                .components()
                .map(|c| c.as_os_str().to_string_lossy().into_owned())
                .collect();
            if comps.is_empty() {
                continue;
            }
            let mut cur = &mut top;
            for c in &comps[..comps.len() - 1] {
                cur = cur.dirs.entry(c.clone()).or_default();
            }
            cur.files.push(comps[comps.len() - 1].clone());
        }
    }

    fn render(node: &Node, prefix: &str, out: &mut String) {
        let n_entries = node.dirs.len() + node.files.len();
        let mut i = 0;
        for (name, child) in &node.dirs {
            i += 1;
            let last = i == n_entries;
            out.push_str(prefix);
            out.push_str(if last { "└── " } else { "├── " });
            out.push_str(name);
            out.push_str("/\n");
            let child_prefix = format!("{}{}", prefix, if last { "    " } else { "│   " });
            render(child, &child_prefix, out);
        }
        for name in &node.files {
            i += 1;
            let last = i == n_entries;
            out.push_str(prefix);
            out.push_str(if last { "└── " } else { "├── " });
            out.push_str(name);
            out.push('\n');
        }
    }

    let mut out = format!(
        "{}/\n",
        root.file_name().and_then(|n| n.to_str()).unwrap_or(".")
    );
    render(&top, "", &mut out);
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn fence_grows_past_embedded_backticks() {
        assert_eq!(longest_backtick_run("no ticks"), 0);
        assert_eq!(longest_backtick_run("a ``` b"), 3);
        assert_eq!(longest_backtick_run("x ````` y ``` z"), 5);
    }

    #[test]
    fn anchors_match_github_slugs() {
        assert_eq!(anchor_for("src/main.rs"), "srcmainrs");
        assert_eq!(
            anchor_for("My File Name.md"),
            "my-file-name-md".replace("-md", "md")
        );
    }

    #[test]
    fn tree_is_recursive() {
        let root = Path::new("C:\\proj");
        let files = vec![
            PathBuf::from("C:\\proj\\src\\a\\deep.rs"),
            PathBuf::from("C:\\proj\\src\\main.rs"),
            PathBuf::from("C:\\proj\\README.md"),
        ];
        let tree = generate_tree(root, &files);
        assert!(tree.contains("├── src/") || tree.contains("└── src/"));
        assert!(
            tree.contains("│   ├── a/") || tree.contains("    ├── a/"),
            "{}",
            tree
        );
        assert!(tree.contains("deep.rs"));
        assert!(tree.contains("README.md"));
    }
}
