use std::path::{Path, PathBuf};
use std::fs::File;
use std::io::{BufWriter, Write, BufReader, Read};
use std::collections::BTreeMap;
use std::sync::atomic::{AtomicBool, Ordering};
use anyhow::Result;
use memmap2::MmapOptions;
use rayon::prelude::*;

const MAX_FILE_SIZE: u64 = 50 * 1024 * 1024; // 50MB
const MMAP_THRESHOLD: usize = 16 * 1024; // 16KB

/// Original merge function (backward compatible)
pub fn merge_files(
    root: &Path,
    files: &[PathBuf],
    output: &Path,
    include_tree: bool,
) -> Result<usize> {
    let cancel_flag = AtomicBool::new(false);
    let mut files_processed = 0;
    let mut files_skipped = 0;
    merge_files_with_progress(
        root,
        files,
        output,
        include_tree,
        &cancel_flag,
        |_, _, _| {},
        &mut files_processed,
        &mut files_skipped,
    )
}

/// Merge files with progress reporting and cancellation support
#[allow(clippy::too_many_arguments)]
pub fn merge_files_with_progress<F>(
    root: &Path,
    files: &[PathBuf],
    output: &Path,
    include_tree: bool,
    cancel_flag: &AtomicBool,
    mut progress_callback: F,
    files_processed: &mut usize,
    files_skipped: &mut usize,
) -> Result<usize>
where
    F: FnMut(usize, usize, &str),
{
    let mut writer = BufWriter::with_capacity(256 * 1024, File::create(output)?);
    let mut total_bytes = 0usize;
    let total_files = files.len();

    // Write header
    let folder_name = root.file_name()
        .and_then(|n| n.to_str())
        .map(crate::security::sanitize_filename)
        .unwrap_or_else(|| "Project".to_string());

    writeln!(writer, "# {} - Merged Codebase\n", folder_name)?;
    writeln!(writer, "> Generated by TurboMerger v7.1")?;
    writeln!(writer, "> Files: {}", files.len())?;
    writeln!(writer, "> Source: {}\n", root.display())?;
    writeln!(writer, "---\n")?;

    // Generate tree if not too large
    if include_tree {
        let tree = generate_tree(root, files);
        writeln!(writer, "## Project Structure\n")?;
        writeln!(writer, "```")?;
        write!(writer, "{}", tree)?;
        writeln!(writer, "```\n")?;
        writeln!(writer, "---\n")?;
    }

    // Process files in parallel, collect results
    let results: Vec<_> = files.par_iter()
        .enumerate()
        .filter_map(|(idx, path)| {
            // Check cancellation
            if cancel_flag.load(Ordering::Relaxed) {
                return None;
            }

            match process_file_safe(path, root) {
                Ok((relative, content)) => Some((idx, relative, content, false)),
                Err(_) => Some((idx, String::new(), String::new(), true)), // skipped
            }
        })
        .collect();

    // Sort by original index to maintain order
    let mut sorted_results = results;
    sorted_results.sort_by_key(|(idx, _, _, _)| *idx);

    // Write in order
    for (idx, relative_path, content, was_skipped) in sorted_results {
        // Check cancellation
        if cancel_flag.load(Ordering::Relaxed) {
            break;
        }

        if was_skipped {
            *files_skipped += 1;
            continue;
        }

        // Report progress
        progress_callback(idx + 1, total_files, &relative_path);

        let ext = Path::new(&relative_path)
            .extension()
            .and_then(|e| e.to_str())
            .unwrap_or("txt");

        writeln!(writer, "## {}\n", relative_path)?;
        writeln!(writer, "```{}", ext)?;
        writer.write_all(content.as_bytes())?;
        if !content.ends_with('\n') {
            writeln!(writer)?;
        }
        writeln!(writer, "```\n")?;

        total_bytes += content.len();
        *files_processed += 1;
    }

    writer.flush()?;
    Ok(total_bytes)
}

/// Process a single file with security validation
fn process_file_safe(path: &Path, root: &Path) -> Result<(String, String)> {
    // Validate path is within root (prevent symlink escape)
    if !crate::security::is_within_root(path, root).unwrap_or(false) {
        anyhow::bail!("Path escaped root directory");
    }

    // Skip sensitive files
    if crate::security::is_sensitive_file(path) {
        anyhow::bail!("Sensitive file");
    }

    let metadata = std::fs::metadata(path)?;

    // Check file size
    if metadata.len() > MAX_FILE_SIZE {
        anyhow::bail!("File too large");
    }

    // Skip symlinks
    if metadata.file_type().is_symlink() {
        anyhow::bail!("Symlink skipped");
    }

    let relative = path.strip_prefix(root)
        .map(|p| p.to_string_lossy().replace('\\', "/"))
        .unwrap_or_else(|_| path.to_string_lossy().to_string());

    let file = File::open(path)?;
    let file_size = metadata.len() as usize;

    let content = if file_size > MMAP_THRESHOLD {
        // Memory-mapped read for large files
        let mmap = unsafe { MmapOptions::new().map(&file)? };

        // Quick binary check
        let check_len = 8192.min(file_size);
        if crate::security::is_binary_content(&mmap[..check_len]) {
            anyhow::bail!("Binary file");
        }

        String::from_utf8_lossy(&mmap).into_owned()
    } else if file_size > 0 {
        // Standard read for small files
        let mut reader = BufReader::new(file);
        let mut buffer = Vec::with_capacity(file_size);
        reader.read_to_end(&mut buffer)?;

        let check_len = 8192.min(buffer.len());
        if !buffer.is_empty() && crate::security::is_binary_content(&buffer[..check_len]) {
            anyhow::bail!("Binary file");
        }

        String::from_utf8_lossy(&buffer).into_owned()
    } else {
        String::new()
    };

    Ok((relative, content))
}

fn generate_tree(root: &Path, files: &[PathBuf]) -> String {
    let root_name = root.file_name()
        .and_then(|n| n.to_str())
        .unwrap_or(".");

    // Build directory structure
    let mut dirs: BTreeMap<String, Vec<String>> = BTreeMap::new();

    for file in files {
        if let Ok(relative) = file.strip_prefix(root) {
            let rel_str = relative.to_string_lossy().replace('\\', "/");
            if let Some(pos) = rel_str.rfind('/') {
                let dir = rel_str[..pos].to_string();
                let filename = rel_str[pos+1..].to_string();
                dirs.entry(dir).or_default().push(filename);
            } else {
                dirs.entry(String::new()).or_default().push(rel_str.to_string());
            }
        }
    }

    let mut output = format!("{}/\n", root_name);
    let dir_list: Vec<_> = dirs.keys().cloned().collect();
    let total_dirs = dir_list.len();

    for (dir_idx, dir) in dir_list.iter().enumerate() {
        let is_last_dir = dir_idx == total_dirs - 1;
        let files_in_dir = dirs.get(dir).unwrap();

        if dir.is_empty() {
            // Root level files
            for (i, f) in files_in_dir.iter().enumerate() {
                let is_last = i == files_in_dir.len() - 1 && is_last_dir;
                let connector = if is_last { "└── " } else { "├── " };
                output.push_str(connector);
                output.push_str(f);
                output.push('\n');
            }
        } else {
            // Show directory
            let connector = if is_last_dir { "└── " } else { "├── " };
            output.push_str(connector);
            output.push_str(dir);
            output.push_str("/\n");

            // Show files in directory
            let prefix = if is_last_dir { "    " } else { "│   " };
            for (i, f) in files_in_dir.iter().enumerate() {
                let is_last = i == files_in_dir.len() - 1;
                let file_connector = if is_last { "└── " } else { "├── " };
                output.push_str(prefix);
                output.push_str(file_connector);
                output.push_str(f);
                output.push('\n');
            }
        }
    }

    output
}
