"""Core streaming merge writer for TurboMerger."""

from collections import defaultdict
from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path
from typing import Callable, Optional, TextIO

from turbomerger.detector import (
    collect_files,
    get_language_for_syntax,
    is_binary,
    is_pdf,
    should_skip_file,
)
from turbomerger.pdf_reader import extract_pdf_text
from turbomerger.sentinel import SecretMatch, check_for_secrets, is_secret_file


def generate_tree(root: Path, files: list[Path], max_depth: int = 4) -> str:
    """
    Generate ASCII directory tree from list of files.

    Args:
        root: Root directory path.
        files: List of file paths to include in tree.
        max_depth: Maximum directory depth to show.

    Returns:
        ASCII tree string.
    """
    # Build directory structure
    tree_dict: dict = {}

    for file_path in files:
        try:
            rel_path = file_path.relative_to(root)
            parts = rel_path.parts

            # Limit depth
            if len(parts) > max_depth:
                parts = parts[:max_depth - 1] + ("...",)

            current = tree_dict
            for part in parts[:-1]:
                if part not in current:
                    current[part] = {}
                current = current[part]

            # Add file (use None to mark as file)
            if parts:
                current[parts[-1]] = None
        except ValueError:
            continue

    # Convert to ASCII tree
    lines = [f"{root.name}/"]

    def _build_tree(d: dict, prefix: str = "") -> None:
        items = sorted(d.items(), key=lambda x: (x[1] is not None, x[0].lower()))
        for i, (name, subtree) in enumerate(items):
            is_last = i == len(items) - 1
            connector = "└── " if is_last else "├── "
            extension = "    " if is_last else "│   "

            if subtree is None:
                # It's a file
                lines.append(f"{prefix}{connector}{name}")
            else:
                # It's a directory
                lines.append(f"{prefix}{connector}{name}/")
                _build_tree(subtree, prefix + extension)

    _build_tree(tree_dict)

    return "\n".join(lines)


@dataclass
class MergeStats:
    """Statistics for a merge operation."""

    total_files: int = 0
    processed_files: int = 0
    skipped_files: int = 0
    error_files: int = 0
    total_chars: int = 0
    truncated_files: int = 0
    pdf_files: int = 0
    secret_files: int = 0
    skipped_reasons: dict[str, int] = field(default_factory=dict)


@dataclass
class FileProcessResult:
    """Result of processing a single file."""

    path: Path
    relative_path: str
    content: Optional[str] = None
    error: Optional[str] = None
    is_skipped: bool = False
    skip_reason: str = ""
    is_truncated: bool = False
    is_pdf: bool = False
    char_count: int = 0
    is_secret: bool = False
    secret_types: list[str] = field(default_factory=list)
    secret_matches: list[SecretMatch] = field(default_factory=list)
    language: str = ""


class StreamingMerger:
    """Streaming merge writer that processes files incrementally."""

    def __init__(
        self,
        project_root: Path,
        output_path: Path,
        mode: str = "smart",
        max_file_size_mb: float = 2.0,
        max_chars_per_file: int = 100_000,
    ):
        """
        Initialize the streaming merger.

        Args:
            project_root: Root directory of the project to merge.
            output_path: Path to write the merged output.
            mode: "smart" for code-only, "complete" for all text.
            max_file_size_mb: Maximum file size in MB to process.
            max_chars_per_file: Maximum characters per file before truncation.
        """
        self.project_root = project_root
        self.output_path = output_path
        self.mode = mode
        self.max_file_bytes = int(max_file_size_mb * 1024 * 1024)
        self.max_chars = max_chars_per_file
        self.stats = MergeStats()
        self._output_file: Optional[TextIO] = None

    def _write_header(self, files: list[Path]) -> None:
        """Write the document header with project tree."""
        assert self._output_file is not None

        project_name = self.project_root.name
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        mode_desc = "Smart Code Scan" if self.mode == "smart" else "Complete Scan"

        header = f"""# {project_name} - Merged Codebase

> Generated by TurboMerger v4.0
> Timestamp: {timestamp}
> Mode: {mode_desc}
> Source: {self.project_root}

---

## Project Structure

```
{generate_tree(self.project_root, files)}
```

---

## Table of Contents

"""
        self._output_file.write(header)

    def _write_toc(self, files: list[Path]) -> None:
        """Write table of contents."""
        assert self._output_file is not None

        for file_path in files:
            rel_path = file_path.relative_to(self.project_root)
            anchor = str(rel_path).replace("\\", "/").replace("/", "-").replace(".", "-")
            self._output_file.write(f"- [{rel_path}](#{anchor})\n")

        self._output_file.write("\n---\n\n")

    def _process_file(self, file_path: Path, cancel_check: Optional[Callable] = None) -> FileProcessResult:
        """
        Process a single file.

        Args:
            file_path: Path to the file.
            cancel_check: Optional callback that returns True if cancelled.

        Returns:
            FileProcessResult with content or error information.
        """
        rel_path = str(file_path.relative_to(self.project_root))
        result = FileProcessResult(
            path=file_path,
            relative_path=rel_path,
            language=get_language_for_syntax(file_path),
        )

        # Check for cancellation
        if cancel_check and cancel_check():
            result.is_skipped = True
            result.skip_reason = "CANCELLED"
            return result

        # Check if it's a secret file (by name)
        is_secret, secret_reason = is_secret_file(file_path)
        if is_secret:
            result.is_skipped = True
            result.is_secret = True
            result.skip_reason = secret_reason
            result.secret_types = [secret_reason]
            return result

        # Check file size
        try:
            file_size = file_path.stat().st_size
        except OSError as e:
            result.error = f"Cannot access file: {e}"
            result.is_skipped = True
            result.skip_reason = "ACCESS_ERROR"
            return result

        if file_size > self.max_file_bytes:
            result.is_skipped = True
            result.skip_reason = "TOO_LARGE"
            return result

        # Check for cancellation before I/O
        if cancel_check and cancel_check():
            result.is_skipped = True
            result.skip_reason = "CANCELLED"
            return result

        # Check if binary
        if is_binary(file_path):
            result.is_skipped = True
            result.skip_reason = "BINARY"
            return result

        # Handle PDF
        if is_pdf(file_path):
            result.is_pdf = True
            content = extract_pdf_text(file_path)
            if content:
                result.content = content
                result.char_count = len(content)
            else:
                result.is_skipped = True
                result.skip_reason = "PDF_EXTRACTION_FAILED"
            return result

        # Read text file
        try:
            with open(file_path, "r", encoding="utf-8", errors="replace") as f:
                content = f.read(self.max_chars + 1)

            if len(content) > self.max_chars:
                content = content[: self.max_chars]
                result.is_truncated = True
                content += f"\n\n[... Truncated at {self.max_chars:,} characters ...]"

            result.content = content
            result.char_count = len(content)

            # Scan for secrets in content
            secret_result = check_for_secrets(content, file_path)
            if secret_result.has_secrets:
                result.is_secret = True
                result.secret_matches = secret_result.matches
                result.secret_types = list({m.secret_type for m in secret_result.matches})

        except Exception as e:
            result.error = str(e)
            result.is_skipped = True
            result.skip_reason = "READ_ERROR"

        return result

    def _write_file_section(self, result: FileProcessResult) -> None:
        """Write a file section to the output."""
        assert self._output_file is not None

        rel_path = result.relative_path.replace("\\", "/")
        lang = result.language or ""

        # File header with status indicator
        if result.is_pdf:
            indicator = "[PDF]"
        elif result.is_truncated:
            indicator = "[TRUNCATED]"
        elif result.is_secret:
            indicator = "[SECRETS DETECTED]"
        else:
            indicator = ""

        self._output_file.write(f"\n## {rel_path} {indicator}\n\n")

        if result.error:
            self._output_file.write(f"**Error:** {result.error}\n\n")
        elif result.content:
            self._output_file.write(f"```{lang}\n")

            self._output_file.write(result.content)

            if not result.content.endswith("\n"):
                self._output_file.write("\n")

            self._output_file.write("```\n")

    def _write_footer(self) -> None:
        """Write the document footer with statistics and token estimation."""
        assert self._output_file is not None

        # BUG #4 FIX: Add token estimation (chars / 4 is rough GPT-4 estimate)
        estimated_tokens = self.stats.total_chars // 4

        footer = f"""
---

## Merge Statistics

| Metric | Value |
|--------|-------|
| Total Files Scanned | {self.stats.total_files} |
| Files Processed | {self.stats.processed_files} |
| Files Skipped | {self.stats.skipped_files} |
| Files with Errors | {self.stats.error_files} |
| PDF Files | {self.stats.pdf_files} |
| Truncated Files | {self.stats.truncated_files} |
| Secret Files Detected | {self.stats.secret_files} |
| Total Characters | {self.stats.total_chars:,} |
| Estimated Tokens | ~{estimated_tokens:,} |

"""

        if self.stats.skipped_reasons:
            footer += "### Skip Reasons\n\n"
            for reason, count in sorted(self.stats.skipped_reasons.items()):
                footer += f"- **{reason}**: {count}\n"

        footer += f"\n---\n*Generated by TurboMerger v4.0*\n"

        self._output_file.write(footer)

    def merge(
        self,
        progress_callback: Optional[Callable] = None,
        cancel_check: Optional[Callable] = None,
    ) -> tuple[MergeStats, list[FileProcessResult]]:
        """
        Execute the merge operation.

        Args:
            progress_callback: Optional callback(current, total, filename) for progress.
            cancel_check: Optional callback that returns True if cancelled.

        Returns:
            Tuple of (MergeStats, list of FileProcessResult) with operation results.
        """
        # Collect files
        files = collect_files(self.project_root, self.mode)
        self.stats.total_files = len(files)

        # Store all results for security reporting
        all_results: list[FileProcessResult] = []

        # Open output file
        self._output_file = open(self.output_path, "w", encoding="utf-8")

        try:
            # Write header with project tree
            self._write_header(files)
            self._write_toc(files)

            # Process each file
            for i, file_path in enumerate(files):
                # Check for cancellation
                if cancel_check and cancel_check():
                    break

                # Report progress
                if progress_callback:
                    progress_callback(i + 1, len(files), file_path.name)

                # Check skip status
                skip, reason = should_skip_file(file_path, self.mode)
                if skip:
                    self.stats.skipped_files += 1
                    self.stats.skipped_reasons[reason] = (
                        self.stats.skipped_reasons.get(reason, 0) + 1
                    )
                    continue

                # Process file
                result = self._process_file(file_path, cancel_check)
                all_results.append(result)

                if result.is_skipped:
                    self.stats.skipped_files += 1
                    self.stats.skipped_reasons[result.skip_reason] = (
                        self.stats.skipped_reasons.get(result.skip_reason, 0) + 1
                    )
                    if result.is_secret:
                        self.stats.secret_files += 1
                elif result.error:
                    self.stats.error_files += 1
                    self._write_file_section(result)
                else:
                    self.stats.processed_files += 1
                    self.stats.total_chars += result.char_count

                    if result.is_pdf:
                        self.stats.pdf_files += 1
                    if result.is_truncated:
                        self.stats.truncated_files += 1
                    if result.is_secret:
                        self.stats.secret_files += 1

                    self._write_file_section(result)

            # Write footer
            self._write_footer()

        finally:
            self._output_file.close()
            self._output_file = None

        return self.stats, all_results


def merge_project(
    project_root: Path,
    output_path: Optional[Path] = None,
    mode: str = "smart",
    max_file_size_mb: float = 2.0,
    max_chars_per_file: int = 100_000,
    progress_callback: Optional[Callable] = None,
    cancel_check: Optional[Callable] = None,
) -> tuple[Path, MergeStats, list[FileProcessResult]]:
    """
    Convenience function to merge a project.

    Args:
        project_root: Root directory of the project.
        output_path: Output file path (default: Downloads folder).
        mode: "smart" or "complete".
        max_file_size_mb: Max file size in MB.
        max_chars_per_file: Max chars per file.
        progress_callback: Optional progress callback.
        cancel_check: Optional callback that returns True if cancelled.

    Returns:
        Tuple of (output_path, stats, all_results).
    """
    if output_path is None:
        downloads = Path.home() / "Downloads"
        downloads.mkdir(exist_ok=True)
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        output_path = downloads / f"{project_root.name}_{timestamp}.merged.md"

    merger = StreamingMerger(
        project_root=project_root,
        output_path=output_path,
        mode=mode,
        max_file_size_mb=max_file_size_mb,
        max_chars_per_file=max_chars_per_file,
    )

    stats, all_results = merger.merge(
        progress_callback=progress_callback,
        cancel_check=cancel_check,
    )

    return output_path, stats, all_results
